# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: Run all the test suite
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-all-tests:
    env:
      PORT: 3333
      HOST: '0.0.0.0'
      NODE_ENV: testing
      APP_KEY: WVhRjZ3QeYrajag9KskwMWcVFnfzV2Jp
      DRIVE_DISK: local
      SESSION_DRIVER: cookie
      CACHE_VIEWS: false
      CDN_S3_KEY: the_s3_cdn_key
      CDN_S3_SECRET: the_s3_cdn_secret
      CDN_S3_REGION: ams3
      CDN_S3_ENDPOINT: 'https://ams3.digitaloceanspaces.com'
      CDN_S3_BUCKET: ivanprats-cdn

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      # https://github.com/actions/cache && https://github.com/actions/cache/blob/main/examples.md#node---npm
      - name: Cache node_modules
        uses: actions/cache@v2
        id: node_modules_cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-cache-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-${{ matrix.node-version }}-
            ${{ runner.os }}-npm-cache-

      - name: Install dependencies
        if: steps.node_modules_cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Unit tests
        env:
          TESTING_TYPE: unit
        run: npm run test:raw -- --no-db

      - name: Compile front-end assets in production mode into /public/assets
        run: npm run build-frontend

      - name: Run Integration tests
        env:
          TESTING_TYPE: integration
        run: npm run test:raw -- --no-migrations-rollback

      - name: Run System tests
        env:
          TESTING_TYPE: system
        run: npm run test:raw -- --no-migrations-rollback
